title: Is security a true proposition or a false one?
description: "Something about cyber security"
author:
  name: "Justin Gu"
  email: "n1ceman@protonmail.com"
  url: "https://gsharpsh00ter.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Justin Gu"
year : "2020"
